<?xml version="1.0" encoding="utf-8"?><Database Name="Transportation" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MUSTAFA-PC\SQLEXPRESS;Initial Catalog=Transportation;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TransportationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AREA_COORDINATES" Member="AREA_COORDINATEs">
    <Type Name="AREA_COORDINATE">
      <Column Name="AREA_COORDINATE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AREA_NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="COORDS" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IS_CONTAINER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>