#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Transportation")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TransportationConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AREA_COORDINATE> AREA_COORDINATEs
	{
		get
		{
			return this.GetTable<AREA_COORDINATE>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AREA_COORDINATES")]
public partial class AREA_COORDINATE
{
	
	private int _AREA_COORDINATE_ID;
	
	private string _AREA_NAME;
	
	private string _COORDS;
	
	private int _IS_CONTAINER;
	
	public AREA_COORDINATE()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_COORDINATE_ID", DbType="Int NOT NULL")]
	public int AREA_COORDINATE_ID
	{
		get
		{
			return this._AREA_COORDINATE_ID;
		}
		set
		{
			if ((this._AREA_COORDINATE_ID != value))
			{
				this._AREA_COORDINATE_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string AREA_NAME
	{
		get
		{
			return this._AREA_NAME;
		}
		set
		{
			if ((this._AREA_NAME != value))
			{
				this._AREA_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COORDS", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string COORDS
	{
		get
		{
			return this._COORDS;
		}
		set
		{
			if ((this._COORDS != value))
			{
				this._COORDS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_CONTAINER", DbType="Int NOT NULL")]
	public int IS_CONTAINER
	{
		get
		{
			return this._IS_CONTAINER;
		}
		set
		{
			if ((this._IS_CONTAINER != value))
			{
				this._IS_CONTAINER = value;
			}
		}
	}
}
#pragma warning restore 1591
